project:
  type: book

execute:
  freeze: auto

book:
  title: "Use of Musculoskeletal Rodent Models for Investigating Neuromuscular Injury and Rehabilation"
  author: "Hudson Burke"
  search: true
  repo-url: https://github.com/hudsonburke/thesis/
  downloads: [pdf, docx, epub]
  chapters:
    - index.qmd
    - acknowledgements.qmd
    - chapters/01-introduction.qmd
    - chapters/02-rat-vml.qmd
    - chapters/03-normalization.qmd
    - chapters/04-rat-model.qmd
    - chapters/05-tsl-optimization.qmd
    - chapters/06-muscle-analysis.qmd
    - chapters/07-conclusions.qmd
    - references.qmd
    - appendices/A-young-attachments.qmd
    - appendices/B-rajagopal-mtl.qmd
    - appendices/C-movedb.qmd

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark: darkly
      light: flatly
      # - cosmo
      # - brand
    code-fold: true
  pdf:
    documentclass: scrreprt
    echo: false
  docx:
    toc: true
    execute:
      echo: false
      warning: false
