# Tendon Slack Length Optimization

This chapter draws heavily from the abstract and poster presented at American Society of Biomechanics (ASB) 2025:
"Effects of error function selection and normalized fiber length range in numerical estimation of tendon slack length"
Those materials can be found at the [ASB2025-TSL-Optimization repository](https://github.com/hudsonburke/ASB2025-TSL-Optimization).

## Introduction
In musculoskeletal models incorporating Hill-type muscles, parameters must be specified to determine the forces generated by the musculotendon unit. One of the most influential parameters is tendon slack length. Tendon slack length is originally posited as a representation of the length at which the tendon begins to produce a restorative force and has been estimated in various ways throughout literature. This value cannot simply be measured directly as tendons often run parallel to the fibers of the muscle. One of the most popular human models used especially for lower limb gait modeling from Rajagopal [@rajagopalFullBodyMusculoskeletalModel2016] estimates tendon slack length based on the fiber length at a specific joint configuration. Manal [@manalSubjectSpecificEstimatesTendon2004] proposed an optimization technique to minimize the error between tendon slack lengths estimated at a range of muscle lengths using the active and passive force-length curves for the muscle along with the tendon force-length curve. We extend this technique to analyze the effect that normalized fiber length range and different error functions have on the estimated tendon slack lengths in an effort to inform a robust methodology for numerically tuning tendon slack length in new musculoskeletal models. We also analyze the predicted force profiles produced by the musculotendon units during several different kinematic motions after optimization to assess the physiological plausibility of the results.

## Methods

This methodology follows the same concept proposed in Manal [@manalSubjectSpecificEstimatesTendon2004] in that it utilizes equations derived from Zajac [@zajacMuscleTendonProperties1989] to calculate tendon slack length from measured muscle parameters and interpolated force values. The optimization differs by using Sequential Least SQuares Programming (SLSQP) instead of Generalized Reduced Gradient (GRG) as an algorithm for optimization because of its availability and popularity in Python. Furthermore, the active and passive fiber and tendon force length curves were taken from the Millard [@millardFlexingComputationalMuscle2013] muscle as seen in [@fig-millard-fl-curves] instead of Zajac’s curves, and lengths were chosen from the whole range of motion of the muscles instead of a short and long length within ten percent of the minimum and maximum flexion angles and averaging the two for a third middle length. The tendon slack lengths were estimated for the lateral gastrocnemius (gaslat), long head of the biceps femoris (bflh), and the soleus to demonstrate application across muscles of differing architectures in terms of tendon to fiber ratio. In addition to the sum of squared differences between each element originally used by Manal, three additional error functions were utilized: the standard deviation, the variance, and the sum of squared differences between each element and the mean. The model's position was iterated through all of the degrees of freedom to get a minimum of 100 musculotendon lengths for each muscle. Then, SLSQP minimization from the `scipy` [@] optimization library in Python is utilized to minimize the error function of the calculated tendon slack lengths at each musculotendon length. This was performed using a full range of normalized fiber lengths to capture the main force-producing part of the fiber force-length curve, using estimates of the operating range of each muscle during gait as reported by Arnold [@], and using only the ascending portion of the curve as done in Manal [@].

$l^{t}_{s} = \frac{l^{mt}-l^{m}_{o} \cdot \tilde{l}^{m}\cos(\alpha)}{\left[ 1+\frac{\text{eval}\left[\tilde{F}^{m}(\tilde{l}^{m})\right]\cos(\alpha)+0.2375}{37.5} \right]}$

Sum of Squared Difference of Pairs (ssdp):
$\sum_{i}\sum_{j}\left(l^{t}_{s,(i)}-l^{t}_{s,(j)}\right)^{2}$

Sum of Squared Difference from Mean (ssdm):
$\sum\left(l^{t}_{s,(i)}-\bar{l}^{t}_{s}\right)^{2}$

Standard Deviation (std):
$\sqrt{ \frac{\sum\left(l^{t}_{s,(i)}-\bar{l}^{t}_{s}\right)^{2}}{n} }$

Variance (var):

$\frac{\sum\left(l^{t}_{s,(i)}-\bar{l}^{t}_{s}\right)^{2}}{n}$

## Results

{{< embed ../src/ASB2025-TSL-Optimization/analysis.ipynb# >}}


## Discussion

Changing the error functions produced little difference compared to each other, but the range of tendon slack length estimates changed substantially with normalized fiber length range. The tendon slack length plots only show the estimates produced by SSDP, used in Manal’s original method. For each muscle, the tendon slack length estimated at each musculotendon length across a normalized fiber length range of 0.4 to 1.5 is plotted along with the corresponding force range. The highlighted regions show the range of musculotendon lengths in different activities, particularly an athletic cutting motion and squatting. This could introduce activity dependent inaccuracies when the musculotendon length is close to the ends of its range. For example, the tendon slack length estimate for the soleus may work for a squatting motion but not for an athletic cutting motion.

## Application to Rodent Model

As mentioned in @sec-musc-params, many muscles in the rat model lacked values for tendon slack length or had unreliable values, preventing muscle level analyses. To address this, we applied this tendon slack length optimization methodology to estimate tendon slack lengths for all muscles in the rat hindlimb model. With much more limited data on rodent muscle parameters and fiber length ranges, the optimization was only performed using the full normalized fiber length range and the sum of squared differences of pairs (ssdp) error function. For range of motion, we compared the model's full range of motion as well as observed range of motion during normal gait compiled from baseline walking trials from the study detailed in @sec-rat-vml. The results, compared with the parameters from Johnson's papers [@missing-reference] are summarized in @tbl-tsl-comparison.

{{< embed ../src/RatHindlimb/notebooks/tsl_optimization.ipynb#tbl-tsl-comparison >}}

For our model, we chose the tendon slack lengths optimized from the gait kinematics as the model's full range of motion reaches physiologically infeasible configurations.
