---
title: Analysis of Volumetric Muscle Loss Injury and Treatments in the Rodent Lateral Gastrocnemius
author:
  - name: Hudson Burke
    orcid: 0009-0000-2318-9510
    corresponding: true
    email: hudsonburke@virginia.edu
    affiliations:
      - University of Virginia
date: last-modified
bibliography: references.bib
number-sections: true
jupyter: python3
---
## Abstract
Volumetric muscle loss (VML) is a debilitating injury involving removal of skeletal muscle and resulting in permanent functional deficits. This injury is often seen in military personnel from combat wounds and in civilian populations from traumatic accidents. While significant preclinical research is underway, direct comparisons of emerging therapies are rare. This study provides a comprehensive biomechanical comparison of multiple treatment strategies for VML in a rat model. A 20% by-mass VML defect was created in the lateral gastrocnemius (LG) of 48 female Lewis rats, which were divided into six groups (n=8 each): No Repair (NR), Tissue-Engineered Muscle Repair (TEMR),  Healy Hydrogel (HH),  Healy Sponge (HS), and combination therapies of TEMR with the hydrogel (TEMR+HH) or a keratin gel (TEMR+KG). After 24 weeks, we assessed functional recovery using motion capture and force plates to determine spatiotemporal parameters, joint kinematics, and joint kinetics via OpenSim-based inverse dynamics. While no treatment restored full function completely in line with the uninjured controls, some groups demonstrated improvements, showing trends toward normalized ankle kinematics and reduced compensatory kinetic patterns. Others highlighted different gait patterns that compensated for a functional loss about the ankle. These findings highlight the utility of detailed biomechanical analysis in differentiating treatment efficacy for musculoskeletal disorders and provide insight into avenues that may better restore functional outcomes.

## Introduction
Volumetric muscle loss (VML), the traumatic or surgical removal of skeletal muscle beyond the point of natural regeneration, results in severe, permanent functional impairment [@groganVolumetricMuscleLoss2011]. Common in military personnel and civilians following severe trauma, VML involves the loss of muscle fibers leading to non-regenerative scar tissue formation that prevents functional recovery.

Current clinical treatments for VML, such as physical therapy or autologous tissue transfer, have limited efficacy in restoring pre-injury muscle strength and function, often with the drawback of donor site morbidity (Aurora et al., 2014; Garg et al., 2015). This clinical gap has spurred significant preclinical research into regenerative strategies. These approaches often involve biomaterial scaffolds (Grasman et al., 2015; Passipieri et al., 2019), injectable hydrogels (X. Wu et al., 2012), cell-based therapies, and adjunctive treatments like exercise (Corona et al., 2013; Dziki et al., 2016). One significant effort has focused on the development of a tissue engineered muscle repair (TEMR) construct and its use in treating VML in combination with other biomaterials (Corona et al., 2012, 2013; Machingal et al., 2011).

The main metric for assessment of success in these treatments has been force generating capacity of the muscle with the assumption that a return to full muscle force generation capacity would represent a complete return to function. However, this metric does not fully capture the complexities of dynamic, weight-bearing movement as seen in gait, and several studies on human populations have indicated that natural movement is not necessarily restored along with force generation capacity (Buchner et al., 1997; Damiano et al., 2010, 2013; Damiano & Abel, 1998; Topp et al., 1993). Gait analysis offers longitudinal method to assess how an animal functionally adapts to injury and responds to treatment beyond the force generation. Motion analysis tools have become more prevalent in the evaluation of movement pathologies in rodents, including VML (Dienes et al., 2019), arthritis (Allen et al., 2012; Hamilton et al., 2015; Vincelette et al., 2007), nerve injury (Bauman & Chang, 2013; Bennett et al., 2012; Kappos et al., 2017), and spinal cord injury (Beare et al., 2009; Bhimani et al., 2017; Hamers et al., 2001; Koopmans et al., 2005). Many of these studies rely on spatiotemporal parameters to elucidate gait pathologies, but few examine the kinematics and kinetics during locomotion which may provide more insight into compensatory mechanisms that develop in response to injury.

Recent studies from this group have contributed to the understanding of both normal and pathologic rat gait. Dienes (2019) reported changes in gait kinematics in rats with VML injuries to the tibialis anterior during treadmill walking. Hicks and Dienes (2022) established a normative database for rat gait kinematics and kinetics during over-ground walking. These studies have established the necessary 3D motion capture and musculoskeletal modeling methodologies for evaluating the effectiveness of biomaterial constructs as VML treatment strategies.

The goal of this study is to provide a broad, direct comparison of the functional recovery efficacy of different biomaterial treatment strategies for VML in a rat hindlimb model using the lateral gastrocnemius (LG) muscle. We hypothesized that combination therapies providing both a cellular component and a supportive biomaterial would yield the greatest restoration of normal gait biomechanics. By quantifying changes in spatiotemporal parameters, kinematics, and kinetics, we aim to discern which therapeutic strategies most effectively mitigate the pathological compensations associated with VML and demonstrate the efficacy of rodent gait analysis as a modeling platform for various musculoskeletal injuries.

## Methods
### Experimental Design
Forty-eight 12-week-old female Lewis rats were divided into six treatment groups, with eight rats per group. A 20% by-mass volumetric muscle loss (VML) injury was created in the left lateral gastrocnemius (LG) muscle of each animal. The first group was a *No Repair (NR)* control, where the injury site was left empty. The second group received a *Tissue-Engineered Muscle Repair (TEMR)*, which involved filling the site with a cell-seeded bioscaffold. The third and fourth groups received acellular treatments, consisting of either a pro-regenerative *Healy Hydrogel (HH)* or a porous collagen *Healy Sponge (HS)*. The final two groups received combination treatments: one group was given the *TEMR construct with the Healy Hydrogel (TEMR+HH)*, and the other received the *TEMR construct with an acellular keratin gel (TEMR+KG)*. Functional assessment was performed 24 weeks post-surgery and each group was compared to the group that received no repair to clarify trends in recovery or decline. A previously collected dataset of 32 animals was used as the *Control* group.

### Animal Care and Surgical Procedures
All animal procedures were approved by the University of Virginia Animal Care and Use Committee, conducted in compliance with the _Guide for the Care and Use of Laboratory Animals_ , the Animal Welfare Act, and the Implementing Animal Welfare Regulations. Lewis Rats (Charles River Laboratories) were pair-housed in a vivarium accredited by the American Association for the Accreditation of Laboratory Animal Care with ad libitum access to food and water. 

The VML injury surgery was performed in accordance with the procedure outlined in Merritt et al. (2010). The LG was exposed and a 20% distal portion was excised by mass. The assigned repair material was then implanted into the defect following methodologies in the respective literature (Corona et al., 2012, 2013; Machingal et al., 2011). No repair material was implanted in the no repair (NR) group. The overlying fascia was closed with 6-0 vicryl sutures, and the skin was closed with 5-0 prolene using interrupted sutures with skin glue over top to reduce the risk of reopening the incision.

Prior to surgery, slow-release buprenorphine was administered (0.1 mg/kg, subcutaneously). All surgical procedures along with shaving and motion capture marker placement were performed under continuous isoflurane anesthesia inhalation (1.5–2.5%). The depth of anesthesia was monitored by the response of the animal to a slight toe pinch, where the lack of response was considered the surgical plane of anesthesia. A heated water perfusion system was utilized for core temperature maintenance. Post-operative analgesia was provided with quick-release buprenorphine (0.1 mg/kg, subcutaneously) at 36 and 48 hours. No animal required additional analgesia after 48 hours post-surgery as determined by veterinary staff that monitored for pain and distress. 

### Motion Capture and Gait Analysis
After 24 weeks to allow for injury progression or healing, gait data was collected for each rat in the treatment groups. Reflective markers were adhered to bony landmarks on the pelvis and joint locations on the hindlimb based on the set described by Johnson et al. (2008) and utilized in previous studies by this group (Dienes 2019, 2022). Marker locations were: (1) L6 vertebra, (2) 5th caudal vertebra, (3-4) left and right anterior iliac crests, (5-6) left and right greater trochanter of the femur, (7-8) left and right lateral femoral epicondyle, (9-10) left and right lateral malleolus, and (11-12) left and right lateral aspect of the distal end of the 5th metatarsal. After an acclimation period, rats walked along an instrumented walkway while motion was captured with a seven-camera Vicon system recording marker data at 200Hz and synchronized with four in-ground ATI six-axis force transducers recording ground reaction forces at 1000 Hz. A minimum of three successful trials wherein one complete steady-state gait cycle, defined from foot strike to foot strike, per hindlimb without overlap on a force plate during stance phase were collected for each rat at each time point. 

### Gait Modeling and Statistical Analysis
Marker trajectories and ground reaction force data were filtered using a 4th order, low-pass, Butterworth filter (cutoff frequencies of 15 Hz and 100 Hz, respectively). For each rat, a subject specific OpenSim model of the hindlimbs was generated from limb measurements and previously acquired limb anthropometrics (Hicks and Dienes et al., 2022). OpenSim’s inverse kinematic and inverse dynamic tools were used to compute hindlimb joint angles and joint moments. Reported data corresponds to one gait cycle, with the stance and swing phase of the right stride reported independently to minimize the effects of phasing caused by velocity differences. Moments were normalized to total body mass (Nm/kg) except for knee flexion which was normalized to total body mass\*tibia length. **HOW SHOULD THIS BE EXPLAINED** Spatiotemporal parameters (STPs) were calculated in Vicon Nexus using standard definitions as presented in Huxley et al. ( #missingreference). At the 24-week endpoint, STPs were compared to No Repair dataset using unpaired t-tests. For time-series kinematic and kinetic data, Statistical Parametric Mapping (SPM) with unpaired t-tests was used to identify regional significant differences across the gait cycle between groups indicated by highlighted vertical rectangles (Pataky et al. 2016). A red highlighted region indicates significant difference compared to No Repair, and a black highlighted region indicates significant difference compared to Control. Statistical significance was set at α=0.05.

## Results
### Spatiotemporal Parameters
Stride length, step width, and velocity are normalized by leg length calculated by summing the femur and tibia lengths.
```{python}

```
*\^, \^\^, \^\^\^ indicates p < 0.05, 0.01, 0.001 respectively compared to NR*
*\*, \*\*, \*\*\* indicates p < 0.05, 0.01, 0.001 respectively compared to Control*

The No Repair group had a significantly narrower step width and decreased stance percentage compared to the control group. This narrower step width was reflected in nearly every other treatment except the TEMR+HH group.
All groups that received some form of TEMR treatment moved significantly slower compared to both the Control and No Repair groups. This was coupled with significant increases in stance percentages and decreases in stride lengths compared to the Control group. 

### No Repair (NR)

### Healy Hydrogel (HH)

### Healy Sponge (HS)

### Tissue-Engineered Muscle Repair (TEMR)

### TEMR and Hydrogel (TEMR+HH) 

### TEMR and Keratin Gel (TEMR+KG)

## Discussion

### Limitations and Future Directions
This study provides a valuable biomechanical analysis of several different VML repairs at a single time point. A key future direction is a longitudinal analysis to track the evolution of these gait adaptations over the entire 24-week period, which would reveal the time-dependent aspects of recovery and delineate the progression of pathological compensation strategies. Additionally, future studies should include a time-matched, uninjured surgical control group to isolate treatment effects from any changes that may surface as a consequence of natural growth and aging. While the inverse dynamics analysis reveals net joint moments, it falls short of partitioning these into individual muscle force contributions. Future work using advanced musculoskeletal modeling techniques, such as computed muscle control, could estimate these forces and provide deeper insight into neuromuscular compensation patterns. Furthermore, expansion of the model to include the front limbs could uncover further ways that the rats compensate for musculoskeletal deficiencies. Finally, correlating these functional outcomes with histological and molecular analyses of the repair tissue would delineate the biological mechanisms that contribute to the distinction between successful and unsuccessful treatments.

## Conclusion
Volumetric muscle loss causes devastating functional impairments that are not adequately addressed by current clinical practice. This study provides a broad comparison of the long-term functional efficacy of several preclinical regenerative strategies. We found that while no treatment achieved a full return to uninjured function, therapies incorporating a specific pro-regenerative hydrogel produced modest but significant trends toward functional healing, demonstrating mitigated pathological gait compensations. This work emphasizes the utility and importance of detailed biomechanical assessment in evaluating VML treatments and highlights the potential of biomaterials to enhance regenerative outcomes.